### ISSUE TITLE
Not Able To Install jq on Mac

### ISSUE THREAD

**Issue by aayush110** [comp426-2023-spring/a02#1]
The issue is that I am unable to download jq on my MacBook.

**Comment by Lamaab02** [comment]
I would say also try to sudo brew install jq

**Comment by aayush110** [comment]
sadly that did not work :(

**Comment by Lamaab02** [comment]
hhmmm
maybe try this command
$apt-get install -y jq

**Comment by aayush110** [comment]
this did not work either :(

**Comment by Lamaab02** [comment]
this command?
eval $(/opt/homebrew/bin/brew shellenv)

**Comment by aayush110** [comment]
when i do that, this is the erro I am getting: 

-bash: /opt/homebrew/bin/brew: No such file or directory

**Comment by aayush110** [comment]
**Ok, so I think jq installed, but I just wanted to make sure if this is the output I should be getting:** 

==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 1404364, done.
remote: Counting objects: 100% (522/522), done.
remote: Compressing objects: 100% (285/285), done.
remote: Total 1404364 (delta 305), reused 433 (delta 237), pack-reused 1403842
Receiving objects: 100% (1404364/1404364), 536.98 MiB | 30.11 MiB/s, done.
Resolving deltas: 100% (978849/978849), done.
Updating files: 100% (6837/6837), done.
Tapped 3 commands and 6496 formulae (6,848 files, 591MB).
==> Fetching dependencies for jq: oniguruma
==> Fetching oniguruma
==> Downloading https://ghcr.io/v2/homebrew/core/oniguruma/manifests/6.9.8
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/oniguruma/blobs/sha256:680427d2
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Fetching jq
==> Downloading https://ghcr.io/v2/homebrew/core/jq/manifests/1.6-1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:7fee6ea327062b3
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Installing dependencies for jq: oniguruma
==> Installing jq dependency: oniguruma
==> Pouring oniguruma--6.9.8.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/oniguruma/6.9.8: 14 files, 1.4MB
==> Installing jq
==> Pouring jq--1.6.monterey.bottle.1.tar.gz
🍺  /usr/local/Cellar/jq/1.6: 18 files, 1.1MB
==> Running `brew cleanup jq`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Aayushs-MacBook-Air-3:~ aayushmehra$

**Comment by daqichen** [comment]
> when i do that, this is the erro I am getting:
> 
> -bash: /opt/homebrew/bin/brew: No such file or directory

After some research, it looks like the directory for homebrew differs between M1 Mac and Intel Mac, try the line below (for Intel Mac) to see if you still get "no such file or directory":

```
eval "$(/usr/local/Homebrew/bin/brew shellenv)"
```

**Comment by daqichen** [comment]
@aayush110 Suggestion from Professor Martin:

> If brew or port doesn't work for someone, they can use the binary to install it.
> https://stedolan.github.io/jq/download/ All the binaries are listed at the JQ project site.

I am available for OH right now as well if you want to head back to MDH and we can try to troubleshoot over zoom.

**Comment by daqichen** [comment]
@aayush110 Was the issue resolved after trying binary? If so, please remember to resolve/close the Issue.

**Comment by aayush110** [comment]
So I think it worked without the binary. This is the output I got: 

==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 1404364, done.
remote: Counting objects: 100% (522/522), done.
remote: Compressing objects: 100% (285/285), done.
remote: Total 1404364 (delta 305), reused 433 (delta 237), pack-reused 1403842
Receiving objects: 100% (1404364/1404364), 536.98 MiB | 30.11 MiB/s, done.
Resolving deltas: 100% (978849/978849), done.
Updating files: 100% (6837/6837), done.
Tapped 3 commands and 6496 formulae (6,848 files, 591MB).
==> Fetching dependencies for jq: oniguruma
==> Fetching oniguruma
==> Downloading https://ghcr.io/v2/homebrew/core/oniguruma/manifests/6.9.8
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/oniguruma/blobs/sha256:680427d2
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Fetching jq
==> Downloading https://ghcr.io/v2/homebrew/core/jq/manifests/1.6-1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:7fee6ea327062b3
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Installing dependencies for jq: oniguruma
==> Installing jq dependency: oniguruma
==> Pouring oniguruma--6.9.8.monterey.bottle.tar.gz
🍺 /usr/local/Cellar/oniguruma/6.9.8: 14 files, 1.4MB
==> Installing jq
==> Pouring jq--1.6.monterey.bottle.1.tar.gz
🍺 /usr/local/Cellar/jq/1.6: 18 files, 1.1MB
==> Running brew cleanup jq...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see man brew).
Aayushs-MacBook-Air-3:~ aayushmehra$

**Comment by daqichen** [comment]
Perfect, that's similar to my output when installing `jq` with `brew`, you can verify that it is installed with a simple `jq` command to check it is being recognized, but I will close the issue for now.
