### ISSUE TITLE
'Exit is not a function'

### ISSUE THREAD

**Issue by wdrayton** [comp426-2023-spring/a02#10]
#### Description
Autograder testing is claiming that 'exit is not a function' when I try to call 'exit(0)' whenever required

#### Screenshots
<img width="555" alt="Screenshot 2023-02-24 101557" src="https://user-images.githubusercontent.com/69514191/221218039-c38e95bc-100d-4a16-a9cd-fe48fa3e3f8a.png">

#### Steps to resolve
Checking online sources
Looking for a way to import exit
Rereading the instructions
Changing the syntax of the 'exit' function when called (ex. changing from 'exit(0)' to 'exit 0', 'exit()', and 'exit')

**Comment by jdmar3** [comment]
Try `process.exit(0)` instead for an exit without error. 

https://www.geeksforgeeks.org/how-to-exit-process-in-node-js/

https://nodejs.org/api/process.html#event-exit

You would use `process.exit(INTEGER) if there was some error.
The INTEGER encodes the error according to this schema: https://github.com/arzzen/all-exit-error-codes/blob/master/programming-languages/javascript/nodejs.md

**Comment by daqichen** [comment]
@wdrayton Was this issue resolved? If so, please go ahead and close the issue.

**Comment by daqichen** [comment]
Closing this issue now seeing that your latest commit has implemented the suggested changes and they resolved the issue.
