### ISSUE TITLE
Autograder: 'node.cli.js not found'

### ISSUE THREAD

**Issue by wdrayton** [comp426-2023-spring/a02#11]
#### Which autograder check is failing?

npm test

#### What is happening?

Autograder is claiming that 'node.cli.js' cannot be found 

#### Failed workflow run URL

https://github.com/comp426-2023-spring/a02-functions-wdrayton/actions/runs/4263758698/jobs/7420907611

**Comment by daqichen** [comment]
This isn't a bug with the grader, your npm test should not be calling `node.cli.js` but rather `node cli.js`
