### ISSUE TITLE
npm unlink

### ISSUE THREAD

**Issue by croberts808** [comp426-2023-spring/a02#13]
#### Description
When I run npm link, it does what I expect. All of the other test commands work as well. However, when I try to run "npm unlink" at the end of this process, I get the error "npm ERR! Must provide a package name to remove"

#### Steps to reproduce
I reproduced the steps in the assignment instructions and have looked up multiple fixes to this solution, but cannot find any that apply.

**Comment by daqichen** [comment]
@croberts808 have you tried 
```
npm unlink <name of your package as you specified in package.json>
```

**Comment by daqichen** [comment]
Closing this issue seeing that you have passed all the autograder tests.
