### ISSUE TITLE
Autograder: Check for JSON not passing

### ISSUE THREAD

**Issue by croberts808** [comp426-2023-spring/a02#14]
#### Which autograder check is failing?

galosh.js JSON

#### What is happening?
The check fails, even though in my terminal I get what is expected

#### Failed workflow run URL

https://github.com/comp426-2023-spring/a02-functions-croberts808/actions/runs/4316659844/jobs/7532721414

#### What should be happening?

The test should be passing because the result is the same as the autograder expects. 

#### Screenshots of your local test(s)
![terminal](https://user-images.githubusercontent.com/77806710/222508903-d594ac1f-2a51-4655-a888-e189cc2f54d3.png)

#### Why do you think the autograder is failing? 
I may have pulled the files before the autograder was fully uploaded.

**Comment by daqichen** [comment]
@croberts808 I am reading the logs and seeing:
```
Expected:%0ALatitude must be in range%0AActual:%0A{%0A  reason: "Value of type 'Float' required for key 'latitude'.",%0A  error: true%0A}
```

Your output doesn't match the expected: "Latitude must be in range"

Looking at your `cli.js`, I noticed:
```
const response = await fetch('https://api.open-meteo.com/v1/forecast?latitude=' + latitude + '&longitude=' + longitude+ '&daily=precipitation_hours&timezone=' + timezone);
```

So when latitude and longitude are not supplied, there would be an input missing, I would suggest giving `latitude` and `longitude` a number value to fall back on, for example `99999`

**Comment by croberts808** [comment]
I added those default values by saying "var longitude  = 99999" and same for latitude. Now the autograder has tried to run multiple times and it times out.

**Comment by croberts808** [comment]
Actually I fixed it now, thank you!
