### ISSUE TITLE
Runtime error: Auto grader keeps outputting same error message

### ISSUE THREAD

**Issue by parrepu** [comp426-2023-spring/a02#19]
#### What is happening?
I went to Office Hours, and we weren't able to debug the following issues on the autograder. It kept returning "::error::Error: Exit with code: 127 and signal: null" for a few of the tests. He suggested that I post this issue on GitHub. 

#### What does the error say is happening?
"::error::Error: Exit with code: 127 and signal: null".

#### What do you think the error means?
Maybe a certain command is not found, or there are restriction access issues. 

#### Screenshots & Error Log
![autograder_1](https://user-images.githubusercontent.com/69826257/233178231-c94cf040-e292-40cc-be8d-e2be4028acf6.png)
![autograder_2](https://user-images.githubusercontent.com/69826257/233178234-a51f5b09-1a7a-41f5-9f06-5eead1f25bae.png)
![comandline_1](https://user-images.githubusercontent.com/69826257/233178808-e167078f-350e-48a9-9323-c8fd0299ca73.png)
![comandline_2](https://user-images.githubusercontent.com/69826257/233178237-7f108b92-865d-4439-b9f5-4ddd06e2a78b.png)

#### Node.js version
v18.14.2

#### Operating system
Linux LAPTOP-LPCQT12R 5.10.16.3-microsoft-standard-WSL2

**Comment by hetianyuanjames** [comment]
Hi Praneeth, I believe I just identified the issue. In the error message, it says "**/usr/bin/env: 'node // Following should be the first line of the script file': No such file or directory**". You should include "**#!/usr/bin/env node**" only in your first line to indicate it's a script file, and remove the later part.

**Comment by parrepu** [comment]
Thank you! I went ahead and made the following change, and many of the tests that were originally failing are now passing.
