### ISSUE TITLE
Autograder: Timezone flag uses `-t` instead of `-z`

### ISSUE THREAD

**Issue by CheezBallzPi** [comp426-2023-spring/a02#3]
#### Which autograder check is failing?
The ones that use the timezone flag:
- Today Weather
- galosh.js today
- galosh.js tomorrow

#### What is happening?
Tests are failing due to an unexpected flag.

#### Failed workflow run URL
https://github.com/comp426-2023-spring/a02-functions-CheezBallzPi/actions/runs/4088271895

#### What should be happening?
The tests should be using `-z` as mentioned in #2.

#### Screenshots of your local test(s)
![image](https://user-images.githubusercontent.com/14968162/216721018-d24932aa-1395-4ff6-9973-391f16d9edc4.png)

#### Why do you think the autograder is failing? 
The test scripts are using `-t` for the timezone flag instead of `-z`. I confirmed this through an error message my script returned.

**Comment by jdmar3** [comment]
I've updated the autograder to ensure that all of the run commands use the `-z` switch now.

So, we should be good to go!
