### ISSUE TITLE
How to find test cases

### ISSUE THREAD

**Issue by hannesbrinklert** [comp426-2023-spring/a02#5]
Hello,

My code fails on some tests in the grader and I was wondering how you can find what the grader tests in order to do the same test cases on my computer.

**Comment by vennila-t** [comment]
Hello,

Have you tried running npm test? More often than not, the error that appears on the autograder will appear in the terminal when you run that command. This way, you can troubleshoot using the example test case. Make sure this test case is in the package.json file, within 'test:'

Let me know if there are any follow-up questions

**Comment by hannesbrinklert** [comment]
Thanks for the help!
