### ISSUE TITLE
Urgent Issue With npm test

### ISSUE THREAD

**Issue by aayush110** [comp426-2023-spring/a02#6]
Everything seems to be working fine but my npm test is giving this one error over and over again and i have absolutely no idea what is going wrong. Even a TA helped me and could not figure out the error. PLEASE HELP ME! This is for a02 btw

This is what my npm test is throwing out:

a02-functions-aayush110@1.0.0 test
node cli.js -n 35.92 -w 79.05 -z America/New_York

file:///Users/aayushmehra/a02-functions-aayush110/cli.js:78
var rainy = data.daily.precipitation_hours[1];
^

TypeError: Cannot read properties of undefined (reading 'precipitation_hours')
at file:///Users/aayushmehra/a02-functions-aayush110/cli.js:78:26
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by SavitraKulkarni** [comment]
undefined variable

**Comment by aayush110** [comment]
but i do not think it has to be defined, and even the previous ta said that the issue is not with it being "undefined" because it works without any error in the first case where i am using 'precipitation_hours'

**Comment by aayush110** [comment]
the issue is now resolved thanks to TA Mahitha Reddy!

**Comment by beccalewis** [comment]
I'm having the same issue. How did you resolve it?

**Comment by daqichen** [comment]
@beccalewis check to see what `data` object looks like before you reference `perception_hours`:
```
const data = await response.json();
console.log(data);
```
