### ISSUE TITLE
"Unable to locate package jq"

### ISSUE THREAD

**Issue by wdrayton** [comp426-2023-spring/a02#8]
#### Description
Upon trying to install the jq package my computer returns the error "unable to locate package jq"

#### Screenshots

![Screenshot (146)](https://user-images.githubusercontent.com/69514191/217918913-9a27acee-a3cc-45cc-935e-4621ef325c6b.png)

**Comment by daqichen** [comment]
@wdrayton Is this Ubuntu? 

Try `sudo apt-get update` first and then the jq install command.

**Comment by wdrayton** [comment]
Yes, it is Ubuntu.
That fixed things, thanks.
