### ISSUE TITLE
Runtime error: 'import' is unsuccessful

### ISSUE THREAD

**Issue by wdrayton** [comp426-2023-spring/a02#9]
#### What is happening?

The 'import' function of my code is not working even though the repository is set to type 'module'

#### Screenshots

![Screenshot (147)](https://user-images.githubusercontent.com/69514191/221060644-55c8e9b2-088b-4483-89a4-e61620dcba11.png)

![Screenshot (148)](https://user-images.githubusercontent.com/69514191/221060651-c142870d-dce0-47af-908c-84d3acf6ffe4.png)

**Comment by daqichen** [comment]
@wdrayton move `type` to the parent level in your `package.json`

And for the future, please delete the instruction text as the template instructed. Closing this issue now.
